Review update with refactorings

diff --git a/distro/src/bin/hazelcast b/distro/src/bin/hazelcast
--- a/distro/src/bin/hazelcast
+++ b/distro/src/bin/hazelcast
@@ -1,25 +1,19 @@
 #!/usr/bin/env bash
 
+# find the current directory and set HAZELCAST_HOME to one directory upper.
 PRGDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
 export HAZELCAST_HOME=${HAZELCAST_HOME:-$(cd "$PRGDIR/.." >/dev/null; pwd -P)}
 
-#
-function find_RUN_JAVA() {
-    if [ $JAVA_HOME ] ; then
-        RUN_JAVA=$JAVA_HOME/bin/java
-    else
-        RUN_JAVA=`which java 2>/dev/null`
-    fi
+if [ $JAVA_HOME ] ; then
+    RUN_JAVA=$JAVA_HOME/bin/java
+else
+    RUN_JAVA=`which java 2>/dev/null`
+fi
 
-    if [ -z $RUN_JAVA ] ; then
-        echo "Error: Java not found. Please install Java 8 or higher in your PATH or set JAVA_HOME appropriately"
-        exit 1
-    fi
-}
-
-#############
-
-find_RUN_JAVA
+if [ -z $RUN_JAVA ] ; then
+    echo "Error: JRE not found. Please install JRE 8 or higher in your PATH or set JAVA_HOME appropriately"
+    exit 1
+fi
 
 export CLASSPATH="$HAZELCAST_HOME/lib/**"
 
