Forbid .github/release_type in PRs

diff --git a/.github/workflows/publish-packages.yml b/.github/workflows/publish-packages.yml
--- a/.github/workflows/publish-packages.yml
+++ b/.github/workflows/publish-packages.yml
@@ -78,15 +78,21 @@ jobs:
           echo "HZ_VERSION_OSS=$HZ_VERSION_OSS" >> $GITHUB_ENV
           echo "hz_version_oss=$HZ_VERSION_OSS" >> $GITHUB_OUTPUT
 
+      - name: Forbid .github/release_type file
+        if: github.event_name == 'pull_request'
+        run: |
+          if [ -f ".github/release_type" ]; then
+            echo "Error: .github/release_type file is not allowed in the PRs. It's used only during release creation"
+            exit 1
+          fi
+
       - name: Read release type from the file
-        if: github.event_name != 'workflow_dispatch'
         run: |
           RELEASE_TYPE_FILE=.github/release_type
           if [ -f $RELEASE_TYPE_FILE ]; then
               echo "RELEASE_TYPE=$(cat $RELEASE_TYPE_FILE)" >> $GITHUB_ENV
           else
               echo "File '$RELEASE_TYPE_FILE' does not exist."
-              exit 1
           fi
 
       - name: Check which editions should be built
