Use internal snapshot repository for OSS snapshot packages [DI-154] (#207)
- Use internal snapshot maven repository for getting OSS snapshot
distribution zip
- Do not produce brew packages for OSS snapshot as it would expose
password-protected urls

Fixes https://hazelcast.atlassian.net/browse/DI-154

Implemented similar like hazelcast-docker:
https://github.com/hazelcast/hazelcast-docker/pull/774

diff --git a/.github/workflows/publish-brew-package.yml b/.github/workflows/publish-brew-package.yml
--- a/.github/workflows/publish-brew-package.yml
+++ b/.github/workflows/publish-brew-package.yml
@@ -55,10 +55,18 @@ jobs:
           distribution: ${{ env.JAVA_DISTRIBUTION }}
 
       - name: Download the distribution tar.gz file
+        env:
+          HZ_SNAPSHOT_INTERNAL_PASSWORD: ${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}
+          HZ_SNAPSHOT_INTERNAL_USERNAME: ${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
         run: |
-          HZ_PACKAGE_URL=$(mvn --batch-mode dependency:copy -Dartifact=com.hazelcast:${HZ_DISTRIBUTION}-distribution:${HZ_VERSION}:tar.gz \
-          -DoutputDirectory=./ -Dmdep.useBaseVersion=true | grep 'Downloaded from' | grep -Eo "https://[^ >]+${HZ_DISTRIBUTION}-distribution-.*.tar.gz")
-          echo "HZ_PACKAGE_URL=$HZ_PACKAGE_URL" >> $GITHUB_ENV
+          . .github/workflows/build.functions.sh
+          DISTRIBUTION_URL=$(get_hz_dist_tar_gz "${HZ_VERSION}" "${HZ_DISTRIBUTION}")
+          if [[ "$(url_contains_password "$DISTRIBUTION_URL" "$HZ_SNAPSHOT_INTERNAL_PASSWORD")" == "yes" ]]; then
+             echo "Trying to expose a password-protected url of the distribution file, aborting!";
+             exit 1;
+          fi
+          curl --fail --silent --show-error --location "${DISTRIBUTION_URL}" --output distribution.tar.gz 
+          echo "HZ_PACKAGE_URL=${DISTRIBUTION_URL}" >> $GITHUB_ENV
 
       - name: Get homebrew repository
         run: |
@@ -112,3 +120,10 @@ jobs:
         run: |
           source ./common.sh          
           brew uninstall ${{ env.HZ_DISTRIBUTION}}@$BREW_PACKAGE_VERSION
+
+      - name: Store logs as artifact
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: brew-${{ env.HZ_DISTRIBUTION}}-hz.log
+          path: hz.log
