Use internal snapshot repository for OSS snapshot packages [DI-154] [5.5.z]

diff --git a/.github/workflows/publish-brew-package.yml b/.github/workflows/publish-brew-package.yml
--- a/.github/workflows/publish-brew-package.yml
+++ b/.github/workflows/publish-brew-package.yml
@@ -56,9 +56,16 @@ jobs:
 
       - name: Download the distribution tar.gz file
         run: |
-          HZ_PACKAGE_URL=$(mvn --batch-mode dependency:copy -Dartifact=com.hazelcast:${HZ_DISTRIBUTION}-distribution:${HZ_VERSION}:tar.gz \
-          -DoutputDirectory=./ -Dmdep.useBaseVersion=true | grep 'Downloaded from' | grep -Eo "https://[^ >]+${HZ_DISTRIBUTION}-distribution-.*.tar.gz")
-          echo "HZ_PACKAGE_URL=$HZ_PACKAGE_URL" >> $GITHUB_ENV
+          . .github/workflows/build.functions.sh
+          export HZ_SNAPSHOT_INTERNAL_PASSWORD=${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}
+          export HZ_SNAPSHOT_INTERNAL_USERNAME=${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
+          DISTRIBUTION_URL=$(get_hz_dist_tar_gz "${HZ_VERSION}" "${HZ_DISTRIBUTION}")
+          if [[ "DISTRIBUTION_URL" == *"$HZ_SNAPSHOT_INTERNAL_PASSWORD"* ]]; then
+             echo "Trying to expose a password-protected url of the distribution file, aborting!";
+             exit 1;
+          fi
+          curl --fail --silent --show-error --location "$DISTRIBUTION_URL" --output distribution.tar.gz 
+          echo "HZ_PACKAGE_URL=$DISTRIBUTION_URL" >> $GITHUB_ENV
 
       - name: Get homebrew repository
         run: |
