Updates for testing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -96,54 +96,6 @@ jobs:
             -udevopshazelcast:${{ secrets.BINTRAY_SECRET }} \
             "https://api.bintray.com/content/hazelcast/deb/hazelcast/${{ env.RELEASE }}/hazelcast-${{ env.RELEASE }}-all.deb;deb_distribution=stable;deb_component=main;deb_architecture=i386,amd64;publish=1"
 
-      - name: Create & Sign & Upload rpm package
-        run: |
-          sudo mkdir -p /home/runner/rpmbuild/SOURCES/
-          sudo cp ${{ env.ASSET_PATH }} /home/runner/rpmbuild/SOURCES/
-          sed -i 's+%define hzversion.*$+%define hzversion ${{ env.HZ_VERSION }}+g' packages/rpm/hazelcast.spec
-          sed -i 's+Version:.*$+Version:    ${{ env.RELEASE }}+g' packages/rpm/hazelcast.spec
-          cp packages/rpm/.rpmmacros /home/runner/
-          gpg --list-keys
-          sudo printf "${{ secrets.DEVOPS_PRIVATE_KEY }}" | base64 --decode > /home/runner/.gnupg/private.key
-          gpg --batch --import /home/runner/.gnupg/private.key
-          sudo printf 'allow-preset-passphrase' > /home/runner/.gnupg/gpg-agent.conf
-          gpg-connect-agent reloadagent /bye
-          /usr/lib/gnupg2/gpg-preset-passphrase --passphrase ${{ secrets.BINTRAY_PASSPHRASE }} --preset 50907674C38F9E099C35345E246EBBA203D8E107
-          gpg --export -a 'Hazelcast' > RPM-GPG-KEY-Hazelcast
-          sudo rpm --import RPM-GPG-KEY-Hazelcast
-          sudo rpmbuild -bb packages/rpm/hazelcast.spec
-          sudo rpm --addsign /home/runner/rpmbuild/RPMS/noarch/hazelcast-${{ env.RELEASE }}-1.noarch.rpm
-          curl --header "X-GPG-PASSPHRASE: ${{ secrets.BINTRAY_PASSPHRASE }}" -T \
-            /home/runner/rpmbuild/RPMS/noarch/hazelcast-${{ env.RELEASE }}-1.noarch.rpm -udevopshazelcast:${{ secrets.BINTRAY_SECRET }} \
-            "https://api.bintray.com/content/hazelcast/rpm/hazelcast/${{ env.RELEASE }}/hazelcast-${{ env.RELEASE }}-1.noarch.rpm;publish=1"
-
-      - name: Checkout homebrew-hz repo
-        uses: actions/checkout@v2.3.1
-        with:
-          repository: hazelcast/homebrew-hz
-          ref: master
-          token: ${{ secrets.DEVOPS_SECRET }}
-
-      - name: Change the artifact in homebrew-hz
-        run: |
-          sudo cp hazelcast@4.X.rb hazelcast@${{ env.RELEASE }}.rb
-          VERSION_NODOTS=$(echo ${{ env.RELEASE }} | sed 's+\.++g')
-          sed -i "s+class HazelcastAT.* <\(.*$\)+class HazelcastAT${VERSION_NODOTS} <\1+g" hazelcast@${{ env.RELEASE }}.rb
-          sed -i 's+url.*$+url "${{ steps.upload-release-asset.outputs.browser_download_url }}"+g' hazelcast@${{ env.RELEASE }}.rb
-          sed -i 's+sha256.*$+sha256 "${{ env.ASSET_SHASUM }}"+g' hazelcast@${{ env.RELEASE }}.rb
-          sudo rm Aliases/hazelcast
-          ln -s ../hazelcast@${{ env.RELEASE }}.rb Aliases/hazelcast
-
-      - name: Commit changes
-        run: |
-          git config --global user.name 'devOpsHazelcast'
-          git config --global user.email 'devops@hazelcast.com'
-          git add hazelcast@${{ env.RELEASE }}.rb
-          git commit -am "Hazelcast Command Line ${{ env.RELEASE }} release"
-
-      - name: Push to homebrew-hz repo
-        run: git push
-
   verify-deb:
     runs-on: ubuntu-latest
     needs: build
@@ -173,62 +125,62 @@ jobs:
             attempts=$(($attempts+1))
             sleep 1
           done
-
-  verify-rpm:
-    runs-on: ubuntu-latest
-    container: centos:latest
-    needs: build
-    name: CLI Release RPM Verification
-    steps:
-      - uses: actions/checkout@v2.3.2
-
-      - name: Install CLI from rpm
-        run: |
-          yum install -y wget
-          wget https://bintray.com/hazelcast/rpm/rpm -O bintray-hazelcast-rpm.repo
-          mv bintray-hazelcast-rpm.repo /etc/yum.repos.d/
-          yum install -y hazelcast-${{ needs.build.outputs.release }}
-          hz start -c src/test/resources/integration-test-hazelcast.yaml &
-
-      - name: Check IMDG health
-        run: |
-          attempts=0
-          max_attempts=10
-          until $(curl --silent --fail "127.0.0.1:5701/hazelcast/health/ready"); do
-            if [ ${attempts} -eq ${max_attempts} ];then
-                echo "Hazelcast not responding"
-                exit 1
-            fi
-            printf '.'
-            attempts=$(($attempts+1))
-            sleep 1
-          done
-
-  verify-homebrew:
-    runs-on: macos-latest
-    needs: build
-    name: CLI Release Homebrew Verification
-    steps:
-      - uses: actions/checkout@v2.3.2
-
-      - name: Install CLI from homebrew
-        run: |
-          brew tap hazelcast/hz
-          brew install hazelcast@${{ needs.build.outputs.release }}
-
-      - name: Run CLI
-        run: hz start -c src/test/resources/integration-test-hazelcast.yaml &
-
-      - name: Check IMDG health
-        run: |
-          attempts=0
-          max_attempts=10
-          until $(curl --silent --fail "127.0.0.1:5701/hazelcast/health/ready"); do
-            if [ ${attempts} -eq ${max_attempts} ];then
-                echo "Hazelcast not responding"
-                exit 1
-            fi
-            printf '.'
-            attempts=$(($attempts+1))
-            sleep 1
-          done
+#
+#  verify-rpm:
+#    runs-on: ubuntu-latest
+#    container: centos:latest
+#    needs: build
+#    name: CLI Release RPM Verification
+#    steps:
+#      - uses: actions/checkout@v2.3.2
+#
+#      - name: Install CLI from rpm
+#        run: |
+#          yum install -y wget
+#          wget https://bintray.com/hazelcast/rpm/rpm -O bintray-hazelcast-rpm.repo
+#          mv bintray-hazelcast-rpm.repo /etc/yum.repos.d/
+#          yum install -y hazelcast-${{ needs.build.outputs.release }}
+#          hz start -c src/test/resources/integration-test-hazelcast.yaml &
+#
+#      - name: Check IMDG health
+#        run: |
+#          attempts=0
+#          max_attempts=10
+#          until $(curl --silent --fail "127.0.0.1:5701/hazelcast/health/ready"); do
+#            if [ ${attempts} -eq ${max_attempts} ];then
+#                echo "Hazelcast not responding"
+#                exit 1
+#            fi
+#            printf '.'
+#            attempts=$(($attempts+1))
+#            sleep 1
+#          done
+#
+#  verify-homebrew:
+#    runs-on: macos-latest
+#    needs: build
+#    name: CLI Release Homebrew Verification
+#    steps:
+#      - uses: actions/checkout@v2.3.2
+#
+#      - name: Install CLI from homebrew
+#        run: |
+#          brew tap hazelcast/hz
+#          brew install hazelcast@${{ needs.build.outputs.release }}
+#
+#      - name: Run CLI
+#        run: hz start -c src/test/resources/integration-test-hazelcast.yaml &
+#
+#      - name: Check IMDG health
+#        run: |
+#          attempts=0
+#          max_attempts=10
+#          until $(curl --silent --fail "127.0.0.1:5701/hazelcast/health/ready"); do
+#            if [ ${attempts} -eq ${max_attempts} ];then
+#                echo "Hazelcast not responding"
+#                exit 1
+#            fi
+#            printf '.'
+#            attempts=$(($attempts+1))
+#            sleep 1
+#          done
